package model;
// Generated 03-jun-2021 14:09:08 by Hibernate Tools 4.3.1



/**
 * Servicios generated by hbm2java
 */
public class Servicios  implements java.io.Serializable {


     private int numeroservicio;
     private String nombre;
     private Integer precio;
     private Integer idt;
     private String imagen;

    public Servicios() {
    }

	
    public Servicios(int numeroservicio) {
        this.numeroservicio = numeroservicio;
    }
    public Servicios(int numeroservicio, String nombre, Integer precio, Integer idt, String imagen) {
       this.numeroservicio = numeroservicio;
       this.nombre = nombre;
       this.precio = precio;
       this.idt = idt;
       this.imagen = imagen;
    }
   
    public int getNumeroservicio() {
        return this.numeroservicio;
    }
    
    public void setNumeroservicio(int numeroservicio) {
        this.numeroservicio = numeroservicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Integer getIdt() {
        return this.idt;
    }
    
    public void setIdt(Integer idt) {
        this.idt = idt;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public String toString() {
        return numeroservicio + "           " + nombre + "          " + precio + "          "+ idt;
    }


}


